#!/usr/bin/env bash

if [ ! -n "${CORN_HOME+x}" ]; then

  PRG="$0"
  while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
    else
    PRG=`dirname "$PRG"`"/$link"
    fi
  done


  CORN_HOME=`dirname "$PRG"`
  CORN_HOME=`cd "$CORN_HOME" && pwd`
fi

 
# build classpath from all jars in lib
if [ -f /usr/bin/cygpath ]; then
  CP=.
  for i in "$CORN_HOME"/corn*.jar; do
    i=`cygpath --windows "$i"`
    CP="$CP;$i"
  done
  for i in "$CORN_HOME"/lib/*.jar; do
    i=`cygpath --windows "$i"`
    CP="$CP;$i"
  done
else
  if [[ $(uname) = MINGW* ]]; then
    CP_SEPARATOR=";"
  else
    CP_SEPARATOR=":"
  fi
  CP=.
  for i in "$CORN_HOME"/corn*.jar; do
    CP="$CP""$CP_SEPARATOR""$i"
  done
  for i in "$CORN_HOME"/lib/*.jar; do
    CP="$CP""$CP_SEPARATOR""$i"
  done
fi

JAVA_OPTS="${JAVA_OPTS-}"

java -cp "$CP" -Djava.util.logging.SimpleFormatter.format='%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS %4$-6s %2$s %5$s%6$s%n' $JAVA_OPTS org.lorislab.corn.CornExecutor ${1+"$@"}

