sudo: required

env:
  global:    
     - secure: "EoSGMvDSLOGbrCeMlxT0u2Vq4596DjgYKrKOVWct7mLU9F/f6dluaMN1f6nNMGljGDdASziogUuSLoDc5jEDGIfC5p3rq5EPi+j8tBzEhPWOoS471WzBYhAJQz95enm0WLNI2FyzQ3hMMZDvlBO1HRW59Cfv3D/Vr6R7w5uxinwqAiNnzkQ0OyF8AhBpeeVkkTvKWeMYh1gT1rVtqXtaYqH9OSnmLGKuCWpQ/m2BJP6L2V2vZw5plOhH/ZrkYlYXvybPEgnwdxKTLJ1fl6EkTluEsMX3of27SLv1DccpT/zrECUuNIW5FvKmsTzUuo2G2F3J94d7jZVq4qPYyq5+UP7jdFz+6SdRH1bT2Vqdgeb6wvknrBQfldn+C0EiHNNjJtJi8Qd4S9wq9VlFMvMlaICjWea7wK0cVr86LxcZfqm8wjQbUa9fWhVXFv5YKj20YjZhgt26KwE+MY5wtCIlaNvMJRtZWljB/Ilf1I4BH+CJzMB+l8YpDYXiZq7c8VYqHBvXntWcbeULkfpxfUmOZ/tJCIkjOnssER0LqPT4IuJ+q/I75NXZ9f3idxOBaAbrKkN5veMnuCo/X28QIE/5iNdz8RdoeiFc53ao0BmFk6NLOMilqJRjargCmQbGtPiwDjiC2L1RNwvh6+wHv4rFyet3C/GT3j+iYHImiD2y9Fs="
     - secure: "VnWZm97K26YDSoC8t5zYzgbW44DaRj9gks1qPAg+zdJiT3qbxKFjwahiSCk5H2lH+I3K9v4WzRk39J2LfOyQe4IHuu6urCUxvx1QLjcPbkc8Ui2eiLC95jeOrWS/Qb1usEKkR7uZup2UGT3v1y1+WOhTmq0pJZ25thOYy5whzi1r/Iy7xWuaDQawrWkeC7xZ6LFCThiaEevdhuRNQXM1GrPK+3PkgYvex4SvJwb+rhFdD+5QmNUdJWV+DT/0fN8koAdK+ZDgoV8qJU1OizBMNZ0tdtO2EPevHQk60SnK4xsQOI2iKAc6loqWwbiER9aWHX6S3IO+CwJgvpazwxxpRutPPdX3CiiuELNrMur0Ai8JvZFqK2W8g8v9eMWyUxMxibcKbwDlEeJlLUNnztg9i1Pf0VIgZJ8HXpZnG7+70uhutAvEPjMIM6GyMWxfMXQ7sPBNeV9n2N6KiPiFERMuuo0N5FGpJdAEG3HrncoCZPoANNXyJQDWS6nk213dZ9h3jisxI5dhxPyYZ/56HAA63QSxf79INDgU/Kx1YT+qmSW1wPKte3ZaHZDXjyU5J+i8s+EBOiFwDqiiKQ+fJOKI42dlFR6Gh013Da7wq0RrDw78IoSmCt2tG9WdQlmYsV/OIioUtW8awdWxShAfTOqJI5J/z7sSQCe7tfDFmLfVu4k="

language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  
services:
  - docker
  
build: 
    - mvn clean install
    
after_success:    
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
    - export REPO=lorislab/corn
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
    - docker build --tag=$REPO:$TAG .
    - docker push $REPO:$TAG