sudo: required

env:
  global:    
    - secure: "CkShwhDwpqOqNr5R4iczwvLjueOwSgFoYCoIhb4k35jLgslVb+WQCFNTkuAh4aoGL6aj9xUMGp8nemkXe2QOmNvZe/G3qHI54JDeZZExQW83X8yOT/2F/ssbKwa7QCmRANVPn7h2VkVDr9uEcIF/bnAWcHJIqWuOwR9zvJzwyysPWO6OYZbigme9jj+ZENdT+NU689Y5QJGu1KOps9IVYfYMEsvg2xTnQ7tQsGtJsPjPPK9oAgKDD+jnf8STue65dlKH1/0/0XbW/a6wvFf5axo0sIV6vOdZCdPEOxIR8cLoBTdgw4uJnxnXSbseyL9g/fY2BMguuPMHAS88XHd5pk8LnXbjhXWdHYW9mVYg0CIwvsRJfDRnvbNkjNSHp4iu3pqhvUCmDiWVtkWG+UwJ3qcOGbHHCrzuO3fwYi8RgxMsE6qiRybMnujSOX/Xa/Bl4cReY29/LceplwMnkugIXFLPl+nPaOi3JpXDsRFsJi8oMU+XnWnPNXuPm2IbZiZY/woJXacSEr28tsb4sI28/QFu4ISwb59/A5pP7Ua5Er5xXlDkrYFh9W59B1hm6IEqLtCheAm2u/28urZ9CnLN9DG+z7V1Bc0M2EgIuFcigCb8r3KkxQvRuADjZtUupIsKZx6SkFhGI4pIsYND+KkFGbbw+jtAxl8cpL9E2brdQ+w="    
    - secure: h1xoKoiz8TIOefbDl8C5WLDx5iauhjMf/iWDmyMLJ7kv9bcRaIVksrBqC/vPjIFiUdaYSvfcSAbRdAPJj7hNjtKLtfxmvY00u9pwLxTa8kGMityDsdZTJ5z7xiaZSwkSCGd4TgwjuB5GW6kErAkJBknHpTpWgAv8NjzirU+YkGgR+3dzxbPP3wdwYsZBceNzNNWquy03Ix5xTgtGCQMAsRjRD1JcVfPAqlH9FRDa2S4i6rwN/I7ohJLDFacfnop3Eiky0FNiWbd6mR/S37AQsrM/kjTO3/Un4z83oyQAtajbwa7Qfu4NReZp1s2/+O5QmH+ITnakEnvuyRw3wK0D8DlIp5x5lV1Ws3pFFJxW2uvxe0vfV/j5qZ9u33+d+c50jEG+mhfcT5Vsdl6ej0O1KCpekC72T/m4JlC9DhyZoScCDJGHwcjE3MT5jYp23ZQtEZb48L5jNTSpAAmuJ4GrWSuw7pTfmDByWZMqAFw6Ul0yo2j/dfZZDemDbtrh/vH0/jQsVtwKwccnKKFmvRz2RICcwK6DEwMuMcf9HiC2mImPDqeqak0UCJPOtolBD12I2yW6TqW49d1tUe+paSKLE0WpofjEFwUBfHcBzyu9F8mAHdy6uZyg6y+gQVEBFdNg0FXVz2pxMe4Ish1l3iaLqLl82YMqyRwAzfFP1eLtqMc=
      
language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  
services:
  - docker
  
build: 
    - mvn clean install
    
after_success:    
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
    - export REPO=lorislab/corn
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
    - docker build --tag=$REPO:$TAG .
    - docker push $REPO:$TAG